// <auto-generated />
using DAL.App.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.App.Database.Migrations
{
    [DbContext(typeof(MedicalMysteryDbContext))]
    [Migration("20180624105947_ChangedABit")]
    partial class ChangedABit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domains.Disease", b =>
                {
                    b.Property<int>("DiseaseId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.HasKey("DiseaseId");

                    b.ToTable("Diseases");
                });

            modelBuilder.Entity("Domains.Symptom", b =>
                {
                    b.Property<int>("SymptomId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.HasKey("SymptomId");

                    b.ToTable("Symptoms");
                });

            modelBuilder.Entity("Domains.SymptomsInDiseases", b =>
                {
                    b.Property<int>("SymptomId");

                    b.Property<int>("DiseaseId");

                    b.Property<int>("SymptomsInDiseasesId");

                    b.HasKey("SymptomId", "DiseaseId");

                    b.HasAlternateKey("SymptomsInDiseasesId");

                    b.HasIndex("DiseaseId");

                    b.ToTable("SymptomsInDiseases");
                });

            modelBuilder.Entity("Domains.SymptomsInDiseases", b =>
                {
                    b.HasOne("Domains.Disease", "Disease")
                        .WithMany("SymptomsInDiseases")
                        .HasForeignKey("DiseaseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domains.Symptom", "Symptom")
                        .WithMany("SymptomsInDiseases")
                        .HasForeignKey("SymptomId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
